version: '2'

services:
  orbs-network-node-1:
    image: orbs:debug
    extends:
      file: docker-compose.yml
      service: orbs-network-node-1
    command: /go/src/github.com/orbs-network/orbs-network-go/orbs-node

  orbs-network-node-2:
    image: orbs:debug
    extends:
      file: docker-compose.yml
      service: orbs-network-node-2
    command: /go/src/github.com/orbs-network/orbs-network-go/orbs-node

  orbs-network-node-3:
    image: orbs:debug
    extends:
      file: docker-compose.yml
      service: orbs-network-node-3
    command: /go/src/github.com/orbs-network/orbs-network-go/orbs-node

  orbs-e2e:
    image: orbs:debug
    extends:
      file: docker-compose.yml
      service: orbs-e2e
    command: sh -c "sleep 10 && /go/src/github.com/orbs-network/orbs-network-go/e2e.test"

networks:
  orbs-network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.199.0/24
